server:
  port: 8080


---
# druid 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_cctv?characterEncoding=utf-8
    username: root
    password: root
  redis:
    # Redis开关/默认关闭
    enabled: true
    database: 0
    password:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

